### ISSUE TITLE
这个崩

### ISSUE THREAD

**Issue by aquanstudy** [lulululbj/AndroidUtilCodeKTX#4]
java.lang.RuntimeException: Unable to start activity ComponentInfo{luyao.ktx/luyao.util.ktx.mvvm.MvvmActivity}: java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2883)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2958)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.java:77)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:65)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:177)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:145)
        at luyao.util.ktx.base.BaseVMActivity.initVM(BaseVMActivity.kt:24)
        at luyao.util.ktx.base.BaseVMActivity.onCreate(BaseVMActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2836)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2958) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by lulululbj** [comment]
已修复 , 见 [commit](https://github.com/lulululbj/AndroidUtilCodeKTX/commit/bb6025163809e194857894c4d4c8a2e02885faa8)。`BaseVMActivity`  中的 `initVM()` 方法一直放在 `onCreate()` 方法之前执行的。
更新相关依赖之后，`ViewModel` 的初始化好像必须在  `onCreate()`  方法之后了。
